
/* File generated by gen_cfile.py. Should not be modified. */

#include "EPOS_Master_EC60.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 Node_ID = 0x1;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 CAN_bit_rate[18] = "Automatic bit rate";		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 CAN_bit_rate_display[18] = "Automatic bit rate";		/* Mapped at index 0x200A, subindex 0x00 */
UNS8 Active_fieldbus[8] = "CANopen";		/* Mapped at index 0x2010, subindex 0x00 */
UNS64 Additional_identity_Serial_number_complete = 0x602137012031;		/* Mapped at index 0x2100, subindex 0x01 */
UNS32 Custom_persistent_memory[] =		/* Mapped at index 0x210C, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Power_supply_Power_supply_voltage = 0x0;		/* Mapped at index 0x2200, subindex 0x01 */
UNS32 Axis_configuration_Sensors_configuration = 0x100001;		/* Mapped at index 0x3000, subindex 0x01 */
UNS32 Axis_configuration_Control_structure = 0x10111;		/* Mapped at index 0x3000, subindex 0x02 */
UNS32 Axis_configuration_Commutation_sensors = 0x31;		/* Mapped at index 0x3000, subindex 0x03 */
UNS32 Axis_configuration_Axis_configuration_miscellaneous = 0x0;		/* Mapped at index 0x3000, subindex 0x04 */
UNS16 Axis_configuration_Main_sensor_resolution = 0x1000;		/* Mapped at index 0x3000, subindex 0x05 */
UNS16 Axis_configuration_Max_system_speed = 0x1770;		/* Mapped at index 0x3000, subindex 0x06 */
UNS32 Motor_data_Nominal_current = 0xA64;		/* Mapped at index 0x3001, subindex 0x01 */
UNS32 Motor_data_Output_current_limit = 0xA64;		/* Mapped at index 0x3001, subindex 0x02 */
UNS8 Motor_data_Number_of_pole_pairs = 0x7;		/* Mapped at index 0x3001, subindex 0x03 */
REAL32 Motor_data_Thermal_time_constant_winding = 49.700000;		/* Mapped at index 0x3001, subindex 0x04 */
REAL32 Motor_data_Torque_canstant = 103.522000;		/* Mapped at index 0x3001, subindex 0x05 */
UNS32 Digtal_increamental_encoder_1_Digtal_increamental_encoder_1_number_of_pulses = 0x400;		/* Mapped at index 0x3010, subindex 0x01 */
UNS16 Digtal_increamental_encoder_1_Digtal_increamental_encoder_1_type = 0x0;		/* Mapped at index 0x3010, subindex 0x02 */
UNS8 Digtal_increamental_encoder_1_Undefined = 0x0;		/* Mapped at index 0x3010, subindex 0x03 */
INTEGER32 Digtal_increamental_encoder_1_Digtal_increamental_encoder_1_index_position = 0x0;		/* Mapped at index 0x3010, subindex 0x04 */
UNS16 SSI_absolute_encoder_SSI_data_rate = 0x7D0;		/* Mapped at index 0x3012, subindex 0x01 */
UNS32 SSI_absolute_encoder_SSI_number_of_data_bits = 0xC00;		/* Mapped at index 0x3012, subindex 0x02 */
UNS16 SSI_absolute_encoder_SSI_encoder_type = 0x1;		/* Mapped at index 0x3012, subindex 0x03 */
UNS8 SSI_absolute_encoder_nouse = 0x0;		/* Mapped at index 0x3012, subindex 0x04 */
UNS16 SSI_absolute_encoder_SSI_timeout_time = 0x1E;		/* Mapped at index 0x3012, subindex 0x05 */
UNS16 SSI_absolute_encoder_SSI_special_bits_trailing_data = 0x0;		/* Mapped at index 0x3012, subindex 0x06 */
UNS32 SSI_absolute_encoder_SSI_refresh_frequency = 0x30D4;		/* Mapped at index 0x3012, subindex 0x07 */
UNS16 SSI_absolute_encoder_SSI_power_up_time = 0xC8;		/* Mapped at index 0x3012, subindex 0x08 */
UNS32 SSI_absolute_encoder_SSI_position_raw_value = 0x0;		/* Mapped at index 0x3012, subindex 0x09 */
UNS32 SSI_absolute_encoder_SSI_commutation_offset_value = 0x0;		/* Mapped at index 0x3012, subindex 0x0A */
UNS32 SSI_absolute_encoder_SSI_position_bits = 0xC;		/* Mapped at index 0x3012, subindex 0x0B */
UNS16 SSI_absolute_encoder_SSI_special_bits_leading_data = 0x0;		/* Mapped at index 0x3012, subindex 0x0C */
UNS64 SSI_absolute_encoder_SSI_position_raw_value_complete = 0x0;		/* Mapped at index 0x3012, subindex 0x0D */
INTEGER32 current_actual_values_current_actual_value_averaged = 0x0;		/* Mapped at index 0x30D1, subindex 0x01 */
INTEGER32 current_actual_values_current_actual_value = 0x0;		/* Mapped at index 0x30D1, subindex 0x02 */
INTEGER32 Velocity_actual_values_Velocity_actual_value_averaged = 0x0;		/* Mapped at index 0x30D3, subindex 0x01 */
UNS8 Abort_connection_option_code[18] = "Quick stop command";		
UNS16 Error_code = 0x0;
UNS16 Controlword = 0x0;
UNS16 Statusword = 0x0040;
UNS8 Modes_of_operation[21] = "Profile Position Mode";
INTEGER32 Position_demand_value = 0;
INTEGER32 Position_actual_value = 0;
INTEGER32 Velocity_demand_value = 0;
INTEGER32 Velocity_actual_value = 0;
INTEGER32 Target_position = 0;
INTEGER32 Min_position_range_limit = 0;
INTEGER32 Max_position_range_limit = 0;
INTEGER32 Min_position_limit = 0;
INTEGER32 Max_position_limit = 0;
UNS32 Max_profile_velocity = 0x1770;
UNS32 Max_Motor_speed = 0x1770;
UNS32 Profile_velocity = 0x3E8;
UNS32 Profile_acceleration = 0x2710;
UNS32 Profile_deceleration = 0x2710;
UNS32 Quick_stop_deceleration = 0x2710;


/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 EPOS_Master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 EPOS_Master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 EPOS_Master_iam_a_slave = 0;

TIMER_HANDLE EPOS_Master_heartBeatTimers[2] = {TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 EPOS_Master_obj1000 = 0x20192;	/* 131474 */
                    subindex EPOS_Master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 EPOS_Master_obj1001 = 0x0;	/* 0 */
                    subindex EPOS_Master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 EPOS_Master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1003[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex EPOS_Master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1003[0], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1003[1], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1003[2], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1003[3], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1003[4], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 EPOS_Master_obj1005 = 0x80;	/* 128 */
                    subindex EPOS_Master_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 EPOS_Master_obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 EPOS_Master_obj1008[8] = "EPOS4";
                    subindex EPOS_Master_Index1008[] = 
                     {
                       { RO, visible_string, 8, (void*)&EPOS_Master_obj1008, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 EPOS_Master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 EPOS_Master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 EPOS_Master_obj1014 = 0x80;	/* 128 */
                    subindex EPOS_Master_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1014, NULL }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 EPOS_Master_highestSubIndex_obj1016 = 2; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1016[] = 
                    {
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex EPOS_Master_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1016[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1016[1], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 EPOS_Master_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 EPOS_Master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1018_Vendor_ID = 0xFB;	/* 251 */
                    UNS32 EPOS_Master_obj1018_Product_Code = 0x61500000;	/* 1632632832 */
                    UNS32 EPOS_Master_obj1018_Revision_Number = 0x1610000;	/* 23134208 */
                    UNS32 EPOS_Master_obj1018_Serial_Number = 0x37012031;	/* 922820657 */
                    subindex EPOS_Master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 EPOS_Master_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 EPOS_Master_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex EPOS_Master_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 EPOS_Master_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1400_COB_ID_used_by_PDO = 0x220;	/* 544 */
                    UNS8 EPOS_Master_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex EPOS_Master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 EPOS_Master_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1401_COB_ID_used_by_PDO = 0x320;	/* 800 */
                    UNS8 EPOS_Master_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex EPOS_Master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 EPOS_Master_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1402_COB_ID_used_by_PDO = 0x420;	/* 1056 */
                    UNS8 EPOS_Master_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex EPOS_Master_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 EPOS_Master_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1403_COB_ID_used_by_PDO = 0x520;	/* 1312 */
                    UNS8 EPOS_Master_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex EPOS_Master_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 EPOS_Master_highestSubIndex_obj1600 = 12; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex EPOS_Master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[7], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[8], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[9], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[10], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1600[11], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 EPOS_Master_highestSubIndex_obj1601 = 12; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex EPOS_Master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[7], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[8], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[9], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[10], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1601[11], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 EPOS_Master_highestSubIndex_obj1602 = 0; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1602[] = 
                    {
                    };
                    subindex EPOS_Master_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1602, NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 EPOS_Master_highestSubIndex_obj1603 = 0; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1603[] = 
                    {
                    };
                    subindex EPOS_Master_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1603, NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 EPOS_Master_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1800_COB_ID_used_by_PDO = 0x400001A0;	/* 1073742240 */
                    UNS8 EPOS_Master_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex EPOS_Master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 EPOS_Master_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1801_COB_ID_used_by_PDO = 0xC00002A0;	/* 3221226144 */
                    UNS8 EPOS_Master_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex EPOS_Master_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 EPOS_Master_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1802_COB_ID_used_by_PDO = 0xC00003A0;	/* 3221226400 */
                    UNS8 EPOS_Master_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex EPOS_Master_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 EPOS_Master_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1803_COB_ID_used_by_PDO = 0xC00004A0;	/* 3221226656 */
                    UNS8 EPOS_Master_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 EPOS_Master_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 EPOS_Master_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex EPOS_Master_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 EPOS_Master_highestSubIndex_obj1A00 = 12; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex EPOS_Master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[7], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[8], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[9], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[10], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A00[11], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 EPOS_Master_highestSubIndex_obj1A01 = 12; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex EPOS_Master_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[7], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[8], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[9], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[10], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A01[11], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 EPOS_Master_highestSubIndex_obj1A02 = 12; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex EPOS_Master_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[7], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[8], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[9], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[10], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A02[11], NULL }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 EPOS_Master_highestSubIndex_obj1A03 = 12; /* number of subindex - 1*/
                    UNS32 EPOS_Master_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex EPOS_Master_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj1A03, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[7], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[8], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[9], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[10], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&EPOS_Master_obj1A03[11], NULL }
                     };

/* index 0x2000 :   Mapped variable Node_ID */
                    subindex EPOS_Master_Index2000[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Node_ID, NULL }
                     };

/* index 0x2001 :   Mapped variable CAN bit rate */
                    subindex EPOS_Master_Index2001[] = 
                     {
                       { RW, visible_string, 18, (void*)&CAN_bit_rate, NULL }
                     };

/* index 0x200A :   Mapped variable CAN bit rate display */
                    subindex EPOS_Master_Index200A[] = 
                     {
                       { RO, visible_string, 18, (void*)&CAN_bit_rate_display, NULL }
                     };

/* index 0x2010 :   Mapped variable Active fieldbus */
                    subindex EPOS_Master_Index2010[] = 
                     {
                       { RO, visible_string, 8, (void*)&Active_fieldbus, NULL }
                     };

/* index 0x2100 :   Mapped variable Additional identity */
                    UNS8 EPOS_Master_highestSubIndex_obj2100 = 1; /* number of subindex - 1*/
                    subindex EPOS_Master_Index2100[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj2100, NULL },
                       { RO, uint64, sizeof (UNS64), (void*)&Additional_identity_Serial_number_complete, NULL }
                     };

/* index 0x210C :   Mapped variable Custom persistent memory */
                    UNS8 EPOS_Master_highestSubIndex_obj210C = 4; /* number of subindex - 1*/
                    subindex EPOS_Master_Index210C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj210C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Custom_persistent_memory[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Custom_persistent_memory[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Custom_persistent_memory[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Custom_persistent_memory[3], NULL }
                     };

/* index 0x2200 :   Mapped variable Power supply */
                    UNS8 EPOS_Master_highestSubIndex_obj2200 = 1; /* number of subindex - 1*/
                    subindex EPOS_Master_Index2200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj2200, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Power_supply_Power_supply_voltage, NULL }
                     };

/* index 0x3000 :   Mapped variable Axis configuration */
                    UNS8 EPOS_Master_highestSubIndex_obj3000 = 6; /* number of subindex - 1*/
                    subindex EPOS_Master_Index3000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj3000, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Axis_configuration_Sensors_configuration, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Axis_configuration_Control_structure, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Axis_configuration_Commutation_sensors, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Axis_configuration_Axis_configuration_miscellaneous, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Axis_configuration_Main_sensor_resolution, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&Axis_configuration_Max_system_speed, NULL }
                     };

/* index 0x3001 :   Mapped variable Motor data */
                    UNS8 EPOS_Master_highestSubIndex_obj3001 = 5; /* number of subindex - 1*/
                    subindex EPOS_Master_Index3001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj3001, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_data_Nominal_current, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Motor_data_Output_current_limit, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Motor_data_Number_of_pole_pairs, NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Motor_data_Thermal_time_constant_winding, NULL },
                       { RW, real32, sizeof (REAL32), (void*)&Motor_data_Torque_canstant, NULL }
                     };

/* index 0x3010 :   Mapped variable Digtal increamental encoder 1 */
                    UNS8 EPOS_Master_highestSubIndex_obj3010 = 4; /* number of subindex - 1*/
                    subindex EPOS_Master_Index3010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj3010, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Digtal_increamental_encoder_1_Digtal_increamental_encoder_1_number_of_pulses, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Digtal_increamental_encoder_1_Digtal_increamental_encoder_1_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&Digtal_increamental_encoder_1_Undefined, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&Digtal_increamental_encoder_1_Digtal_increamental_encoder_1_index_position, NULL }
                     };

/* index 0x3012 :   Mapped variable SSI absolute encoder */
                    UNS8 EPOS_Master_highestSubIndex_obj3012 = 13; /* number of subindex - 1*/
                    subindex EPOS_Master_Index3012[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj3012, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SSI_absolute_encoder_SSI_data_rate, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SSI_absolute_encoder_SSI_number_of_data_bits, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SSI_absolute_encoder_SSI_encoder_type, NULL },
                       { RW, boolean, sizeof (UNS8), (void*)&SSI_absolute_encoder_nouse, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SSI_absolute_encoder_SSI_timeout_time, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&SSI_absolute_encoder_SSI_special_bits_trailing_data, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SSI_absolute_encoder_SSI_refresh_frequency, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&SSI_absolute_encoder_SSI_power_up_time, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&SSI_absolute_encoder_SSI_position_raw_value, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SSI_absolute_encoder_SSI_commutation_offset_value, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&SSI_absolute_encoder_SSI_position_bits, NULL },
                       { RO, uint16, sizeof (UNS16), (void*)&SSI_absolute_encoder_SSI_special_bits_leading_data, NULL },
                       { RO, uint64, sizeof (UNS64), (void*)&SSI_absolute_encoder_SSI_position_raw_value_complete, NULL }
                     };

/* index 0x30D1 :   Mapped variable current actual values */
                    UNS8 EPOS_Master_highestSubIndex_obj30D1 = 2; /* number of subindex - 1*/
                    subindex EPOS_Master_Index30D1[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj30D1, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&current_actual_values_current_actual_value_averaged, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&current_actual_values_current_actual_value, NULL }
                     };

/* index 0x30D3 :   Mapped variable Velocity actual values */
                    UNS8 EPOS_Master_highestSubIndex_obj30D3 = 1; /* number of subindex - 1*/
                    subindex EPOS_Master_Index30D3[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&EPOS_Master_highestSubIndex_obj30D3, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&Velocity_actual_values_Velocity_actual_value_averaged, NULL }
                     };

	
/**************************************************************************/
/* 自己添加的部分，地址0x60开头                                           */
/**************************************************************************/

/*  数据类型都需要核查一下 */
										 
										 
/* index 0x6007 :   Abort connection option code */	
                    UNS8 EPOS_Master_obj6007[20] = "Quick stop command";
                    subindex EPOS_Master_Index6007[] = 
                     {
                       { RW, visible_string, 20, (void*)&EPOS_Master_obj6007, NULL }
                     };

/* index 0x603F :   Error code */	
										UNS16 EPOS_Master_obj603F = 0x0;
                    subindex EPOS_Master_Index603F[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj603F, NULL }
                     };
										 

/* index 0x6040 :   Controlword */
										UNS16 EPOS_Master_obj6040 = 0x0;
                    subindex EPOS_Master_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj6040, NULL }
                     };
										 		 
/* index 0x6041 :   Statusword */
										UNS16 EPOS_Master_obj6041 = 0x0;
                    subindex EPOS_Master_Index6041[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&EPOS_Master_obj6041, NULL }
                     };
										 
/* index 0x6060 :   Modes of operation */
                    UNS8 EPOS_Master_obj6060[25] = "Profile Position Mode";
                    subindex EPOS_Master_Index6060[] = 
                     {
                       { RW, visible_string, 25, (void*)&EPOS_Master_obj6060, NULL }
                     };

/* index 0x6064 :   Position actual value */
										INTEGER32 EPOS_Master_obj6064 = 0x0;
                    subindex EPOS_Master_Index6064[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&EPOS_Master_obj6064, NULL }
                     };
										 
/* index 0x606C :   Velocity actual value */
										INTEGER32 EPOS_Master_obj606C = 0x0;
                    subindex EPOS_Master_Index606C[] = 
                     {
                       { RW, int32, sizeof (INTEGER32), (void*)&EPOS_Master_obj606C, NULL }
                     };
										 
										 
/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable EPOS_Master_objdict[] = 
{
  { (subindex*)EPOS_Master_Index1000,sizeof(EPOS_Master_Index1000)/sizeof(EPOS_Master_Index1000[0]), 0x1000},
  { (subindex*)EPOS_Master_Index1001,sizeof(EPOS_Master_Index1001)/sizeof(EPOS_Master_Index1001[0]), 0x1001},
  { (subindex*)EPOS_Master_Index1003,sizeof(EPOS_Master_Index1003)/sizeof(EPOS_Master_Index1003[0]), 0x1003},
  { (subindex*)EPOS_Master_Index1005,sizeof(EPOS_Master_Index1005)/sizeof(EPOS_Master_Index1005[0]), 0x1005},
  { (subindex*)EPOS_Master_Index1008,sizeof(EPOS_Master_Index1008)/sizeof(EPOS_Master_Index1008[0]), 0x1008},
  { (subindex*)EPOS_Master_Index1014,sizeof(EPOS_Master_Index1014)/sizeof(EPOS_Master_Index1014[0]), 0x1014},
  { (subindex*)EPOS_Master_Index1016,sizeof(EPOS_Master_Index1016)/sizeof(EPOS_Master_Index1016[0]), 0x1016},
  { (subindex*)EPOS_Master_Index1018,sizeof(EPOS_Master_Index1018)/sizeof(EPOS_Master_Index1018[0]), 0x1018},
  { (subindex*)EPOS_Master_Index1200,sizeof(EPOS_Master_Index1200)/sizeof(EPOS_Master_Index1200[0]), 0x1200},
  { (subindex*)EPOS_Master_Index1400,sizeof(EPOS_Master_Index1400)/sizeof(EPOS_Master_Index1400[0]), 0x1400},
  { (subindex*)EPOS_Master_Index1401,sizeof(EPOS_Master_Index1401)/sizeof(EPOS_Master_Index1401[0]), 0x1401},
  { (subindex*)EPOS_Master_Index1402,sizeof(EPOS_Master_Index1402)/sizeof(EPOS_Master_Index1402[0]), 0x1402},
  { (subindex*)EPOS_Master_Index1403,sizeof(EPOS_Master_Index1403)/sizeof(EPOS_Master_Index1403[0]), 0x1403},
  { (subindex*)EPOS_Master_Index1600,sizeof(EPOS_Master_Index1600)/sizeof(EPOS_Master_Index1600[0]), 0x1600},
  { (subindex*)EPOS_Master_Index1601,sizeof(EPOS_Master_Index1601)/sizeof(EPOS_Master_Index1601[0]), 0x1601},
  { (subindex*)EPOS_Master_Index1602,sizeof(EPOS_Master_Index1602)/sizeof(EPOS_Master_Index1602[0]), 0x1602},
  { (subindex*)EPOS_Master_Index1603,sizeof(EPOS_Master_Index1603)/sizeof(EPOS_Master_Index1603[0]), 0x1603},
  { (subindex*)EPOS_Master_Index1800,sizeof(EPOS_Master_Index1800)/sizeof(EPOS_Master_Index1800[0]), 0x1800},
  { (subindex*)EPOS_Master_Index1801,sizeof(EPOS_Master_Index1801)/sizeof(EPOS_Master_Index1801[0]), 0x1801},
  { (subindex*)EPOS_Master_Index1802,sizeof(EPOS_Master_Index1802)/sizeof(EPOS_Master_Index1802[0]), 0x1802},
  { (subindex*)EPOS_Master_Index1803,sizeof(EPOS_Master_Index1803)/sizeof(EPOS_Master_Index1803[0]), 0x1803},
  { (subindex*)EPOS_Master_Index1A00,sizeof(EPOS_Master_Index1A00)/sizeof(EPOS_Master_Index1A00[0]), 0x1A00},
  { (subindex*)EPOS_Master_Index1A01,sizeof(EPOS_Master_Index1A01)/sizeof(EPOS_Master_Index1A01[0]), 0x1A01},
  { (subindex*)EPOS_Master_Index1A02,sizeof(EPOS_Master_Index1A02)/sizeof(EPOS_Master_Index1A02[0]), 0x1A02},
  { (subindex*)EPOS_Master_Index1A03,sizeof(EPOS_Master_Index1A03)/sizeof(EPOS_Master_Index1A03[0]), 0x1A03},
  { (subindex*)EPOS_Master_Index2000,sizeof(EPOS_Master_Index2000)/sizeof(EPOS_Master_Index2000[0]), 0x2000},
  { (subindex*)EPOS_Master_Index2001,sizeof(EPOS_Master_Index2001)/sizeof(EPOS_Master_Index2001[0]), 0x2001},
  { (subindex*)EPOS_Master_Index200A,sizeof(EPOS_Master_Index200A)/sizeof(EPOS_Master_Index200A[0]), 0x200A},
  { (subindex*)EPOS_Master_Index2010,sizeof(EPOS_Master_Index2010)/sizeof(EPOS_Master_Index2010[0]), 0x2010},
  { (subindex*)EPOS_Master_Index2100,sizeof(EPOS_Master_Index2100)/sizeof(EPOS_Master_Index2100[0]), 0x2100},
  { (subindex*)EPOS_Master_Index210C,sizeof(EPOS_Master_Index210C)/sizeof(EPOS_Master_Index210C[0]), 0x210C},
  { (subindex*)EPOS_Master_Index2200,sizeof(EPOS_Master_Index2200)/sizeof(EPOS_Master_Index2200[0]), 0x2200},
  { (subindex*)EPOS_Master_Index3000,sizeof(EPOS_Master_Index3000)/sizeof(EPOS_Master_Index3000[0]), 0x3000},
  { (subindex*)EPOS_Master_Index3001,sizeof(EPOS_Master_Index3001)/sizeof(EPOS_Master_Index3001[0]), 0x3001},
  { (subindex*)EPOS_Master_Index3010,sizeof(EPOS_Master_Index3010)/sizeof(EPOS_Master_Index3010[0]), 0x3010},
  { (subindex*)EPOS_Master_Index3012,sizeof(EPOS_Master_Index3012)/sizeof(EPOS_Master_Index3012[0]), 0x3012},
  { (subindex*)EPOS_Master_Index30D1,sizeof(EPOS_Master_Index30D1)/sizeof(EPOS_Master_Index30D1[0]), 0x30D1},
  { (subindex*)EPOS_Master_Index30D3,sizeof(EPOS_Master_Index30D3)/sizeof(EPOS_Master_Index30D3[0]), 0x30D3},
	{ (subindex*)EPOS_Master_Index6007,sizeof(EPOS_Master_Index6007)/sizeof(EPOS_Master_Index6007[0]), 0x6007},
	{ (subindex*)EPOS_Master_Index603F,sizeof(EPOS_Master_Index603F)/sizeof(EPOS_Master_Index603F[0]), 0x603F},
	{ (subindex*)EPOS_Master_Index6040,sizeof(EPOS_Master_Index6040)/sizeof(EPOS_Master_Index6040[0]), 0x603F},
	{ (subindex*)EPOS_Master_Index6041,sizeof(EPOS_Master_Index6041)/sizeof(EPOS_Master_Index6041[0]), 0x603F},
	{ (subindex*)EPOS_Master_Index6060,sizeof(EPOS_Master_Index6060)/sizeof(EPOS_Master_Index6060[0]), 0x603F},
	{ (subindex*)EPOS_Master_Index6064,sizeof(EPOS_Master_Index6064)/sizeof(EPOS_Master_Index6064[0]), 0x603F},
	{ (subindex*)EPOS_Master_Index606C,sizeof(EPOS_Master_Index606C)/sizeof(EPOS_Master_Index606C[0]), 0x603F},
};

const indextable * EPOS_Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1003: i = 2;break;
		case 0x1005: i = 3;break;
		case 0x1008: i = 4;break;
		case 0x1014: i = 5;break;
		case 0x1016: i = 6;break;
		case 0x1018: i = 7;break;
		case 0x1200: i = 8;break;
		case 0x1400: i = 9;break;
		case 0x1401: i = 10;break;
		case 0x1402: i = 11;break;
		case 0x1403: i = 12;break;
		case 0x1600: i = 13;break;
		case 0x1601: i = 14;break;
		case 0x1602: i = 15;break;
		case 0x1603: i = 16;break;
		case 0x1800: i = 17;break;
		case 0x1801: i = 18;break;
		case 0x1802: i = 19;break;
		case 0x1803: i = 20;break;
		case 0x1A00: i = 21;break;
		case 0x1A01: i = 22;break;
		case 0x1A02: i = 23;break;
		case 0x1A03: i = 24;break;
		case 0x2000: i = 25;break;
		case 0x2001: i = 26;break;
		case 0x200A: i = 27;break;
		case 0x2010: i = 28;break;
		case 0x2100: i = 29;break;
		case 0x210C: i = 30;break;
		case 0x2200: i = 31;break;
		case 0x3000: i = 32;break;
		case 0x3001: i = 33;break;
		case 0x3010: i = 34;break;
		case 0x3012: i = 35;break;
		case 0x30D1: i = 36;break;
		case 0x30D3: i = 37;break;
		case 0x6007: i = 38;break;
		case 0x603F: i = 39;break;
		case 0x6040: i = 40;break;
		case 0x6041: i = 41;break;
		case 0x6060: i = 42;break;
		case 0x6064: i = 43;break;
		case 0x606C: i = 44;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &EPOS_Master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status EPOS_Master_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index EPOS_Master_firstIndex = {
  8, /* SDO_SVR */
  0, /* SDO_CLT */
  9, /* PDO_RCV */
  13, /* PDO_RCV_MAP */
  17, /* PDO_TRS */
  21 /* PDO_TRS_MAP */
};

const quick_index EPOS_Master_lastIndex = {
  8, /* SDO_SVR */
  0, /* SDO_CLT */
  12, /* PDO_RCV */
  16, /* PDO_RCV_MAP */
  20, /* PDO_TRS */
  24 /* PDO_TRS_MAP */
};

const UNS16 EPOS_Master_ObjdictSize = sizeof(EPOS_Master_objdict)/sizeof(EPOS_Master_objdict[0]); 

CO_Data EPOS_Master_Data = CANOPEN_NODE_DATA_INITIALIZER(EPOS_Master);

