
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef EPOS_MASTER_EC60_H
#define EPOS_MASTER_EC60_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 EPOS_Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * EPOS_Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data EPOS_Master_Data;
extern UNS8 Node_ID;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 CAN_bit_rate[18];		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 CAN_bit_rate_display[18];		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS8 Active_fieldbus[8];		/* Mapped at index 0x2010, subindex 0x00*/
extern UNS64 Additional_identity_Serial_number_complete;		/* Mapped at index 0x2100, subindex 0x01 */
extern UNS32 Custom_persistent_memory[4];		/* Mapped at index 0x210C, subindex 0x01 - 0x04 */
extern UNS16 Power_supply_Power_supply_voltage;		/* Mapped at index 0x2200, subindex 0x01 */
extern UNS32 Axis_configuration_Sensors_configuration;		/* Mapped at index 0x3000, subindex 0x01 */
extern UNS32 Axis_configuration_Control_structure;		/* Mapped at index 0x3000, subindex 0x02 */
extern UNS32 Axis_configuration_Commutation_sensors;		/* Mapped at index 0x3000, subindex 0x03 */
extern UNS32 Axis_configuration_Axis_configuration_miscellaneous;		/* Mapped at index 0x3000, subindex 0x04 */
extern UNS16 Axis_configuration_Main_sensor_resolution;		/* Mapped at index 0x3000, subindex 0x05 */
extern UNS16 Axis_configuration_Max_system_speed;		/* Mapped at index 0x3000, subindex 0x06 */
extern UNS32 Motor_data_Nominal_current;		/* Mapped at index 0x3001, subindex 0x01 */
extern UNS32 Motor_data_Output_current_limit;		/* Mapped at index 0x3001, subindex 0x02 */
extern UNS8 Motor_data_Number_of_pole_pairs;		/* Mapped at index 0x3001, subindex 0x03 */
extern REAL32 Motor_data_Thermal_time_constant_winding;		/* Mapped at index 0x3001, subindex 0x04 */
extern REAL32 Motor_data_Torque_canstant;		/* Mapped at index 0x3001, subindex 0x05 */
extern UNS32 Digtal_increamental_encoder_1_Digtal_increamental_encoder_1_number_of_pulses;		/* Mapped at index 0x3010, subindex 0x01 */
extern UNS16 Digtal_increamental_encoder_1_Digtal_increamental_encoder_1_type;		/* Mapped at index 0x3010, subindex 0x02 */
extern UNS8 Digtal_increamental_encoder_1_Undefined;		/* Mapped at index 0x3010, subindex 0x03 */
extern INTEGER32 Digtal_increamental_encoder_1_Digtal_increamental_encoder_1_index_position;		/* Mapped at index 0x3010, subindex 0x04 */
extern UNS16 SSI_absolute_encoder_SSI_data_rate;		/* Mapped at index 0x3012, subindex 0x01 */
extern UNS32 SSI_absolute_encoder_SSI_number_of_data_bits;		/* Mapped at index 0x3012, subindex 0x02 */
extern UNS16 SSI_absolute_encoder_SSI_encoder_type;		/* Mapped at index 0x3012, subindex 0x03 */
extern UNS8 SSI_absolute_encoder_nouse;		/* Mapped at index 0x3012, subindex 0x04 */
extern UNS16 SSI_absolute_encoder_SSI_timeout_time;		/* Mapped at index 0x3012, subindex 0x05 */
extern UNS16 SSI_absolute_encoder_SSI_special_bits_trailing_data;		/* Mapped at index 0x3012, subindex 0x06 */
extern UNS32 SSI_absolute_encoder_SSI_refresh_frequency;		/* Mapped at index 0x3012, subindex 0x07 */
extern UNS16 SSI_absolute_encoder_SSI_power_up_time;		/* Mapped at index 0x3012, subindex 0x08 */
extern UNS32 SSI_absolute_encoder_SSI_position_raw_value;		/* Mapped at index 0x3012, subindex 0x09 */
extern UNS32 SSI_absolute_encoder_SSI_commutation_offset_value;		/* Mapped at index 0x3012, subindex 0x0A */
extern UNS32 SSI_absolute_encoder_SSI_position_bits;		/* Mapped at index 0x3012, subindex 0x0B */
extern UNS16 SSI_absolute_encoder_SSI_special_bits_leading_data;		/* Mapped at index 0x3012, subindex 0x0C */
extern UNS64 SSI_absolute_encoder_SSI_position_raw_value_complete;		/* Mapped at index 0x3012, subindex 0x0D */
extern INTEGER32 current_actual_values_current_actual_value_averaged;		/* Mapped at index 0x30D1, subindex 0x01 */
extern INTEGER32 current_actual_values_current_actual_value;		/* Mapped at index 0x30D1, subindex 0x02 */
extern INTEGER32 Velocity_actual_values_Velocity_actual_value_averaged;		/* Mapped at index 0x30D3, subindex 0x01 */

#endif // EPOS_MASTER_EC60_H
